## Note
- When we are talking about python library means it is code written by someone else such as "**numpy library**"

## Numpy
- Huge and effieient number manipulation

In [61]:
import numpy as np
x=np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [73]:
x=np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [78]:
x*100#only possible in numpy huge manipulation**power of numpy**x/5

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100,
       2200, 2300, 2400, 2500, 2600, 2700, 2800, 2900, 3000, 3100, 3200,
       3300, 3400, 3500, 3600, 3700, 3800, 3900, 4000, 4100, 4200, 4300,
       4400, 4500, 4600, 4700, 4800, 4900, 5000, 5100, 5200, 5300, 5400,
       5500, 5600, 5700, 5800, 5900, 6000, 6100, 6200, 6300, 6400, 6500,
       6600, 6700, 6800, 6900, 7000, 7100, 7200, 7300, 7400, 7500, 7600,
       7700, 7800, 7900, 8000, 8100, 8200, 8300, 8400, 8500, 8600, 8700,
       8800, 8900, 9000, 9100, 9200, 9300, 9400, 9500, 9600, 9700, 9800,
       9900])

## Numpy Array
- Homogenious datatype

In [80]:
y=np.array([1,2,43,6,4])
y

array([ 1,  2, 43,  6,  4])

## Note
- if we have a single floating point value than whole array will be converterd into float

In [81]:
y=np.array([1.1,2.1,43,6.1,4.1])
y

array([ 1.1,  2.1, 43. ,  6.1,  4.1])

In [82]:
y.dtype
y.size

5

In [83]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr.dtype

dtype('int32')

## Multidimentional array

In [87]:
#import numpy as np
aar7=np.array([1,2,3])
aar7.ndim

1

In [88]:
arr8=np.array([[1,2,3],[4,5,6]])
arr8.ndim

2

In [133]:
## Internal array should contain same mxn didentions
arr9=np.array([[[1,3,2],[4,5,6],[7,8,9]]])
arr9

array([[[1, 3, 2],
        [4, 5, 6],
        [7, 8, 9]]])

In [121]:
arr9=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr9.ndim

3

In [135]:
arr10=np.array([[[1,3,2],[4,5,6]],[[7,8,9],[7,8,9]]])
print(arr10.shape)#(2, 2, 3),(internal arrays,internal array further,internal array,values in each array )
print(arr10.size)
print(arr10.ndim)
print(arr10.dtype)
arr10

(2, 2, 3)
12
3
int32


array([[[1, 3, 2],
        [4, 5, 6]],

       [[7, 8, 9],
        [7, 8, 9]]])

In [147]:
x=np.arange(30)#np.zero(10),np.one(10)

x=x.reshape(2,3,5)#x=x.reshape(2,3)2 internal arrays with 3 elements in each

x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [159]:
x=np.arange(30,50,5)#(starting include,ending exclude,each element with ddition)
print(x)
print(np.zeros(10),np.ones(10))
np.ones(10).reshape(2,5).astype('int')

[30 35 40 45]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [164]:
#arr9=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr9.ravel()#convert ndim into 1 dimentional array

array([1, 3, 2, 4, 5, 6, 7, 8, 9])

In [166]:

pwd#present working directory

'C:\\Users\\DANI\\Jupyter Programs'